ci: fix Helm chart repositories URLs
The original Helm repositories are no longer available, hence CI fails
with

```
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

Pointing Helm to the new repositories instead (both `stable` and
`incubator`).

See: https://helm.sh/blog/new-location-stable-incubator-charts/
See: https://github.com/scality/Zenko/pull/1150#issuecomment-781164748